_target_: nets.ConceptEncoder

backbone: 
  _target_: nets.backbones.custom_CNN #nets.backbones.resnet18_backbone #nets.backbones.resnet50_backbone #nets.backbones.mlp_backbone #nets.whitened_resnet.whitened_resnet18 #

cfg_optim: '<OPTIM>'
num_classes: 3 #1235

