_target_: nets.LEACE_end2end 

backbone: 
  _target_: nets.backbones.resnet18_backbone
  pretrained: True
  
encoder: '<ENCODER>'
cfg_optim: '<OPTIM>'
num_classes: 10
alpha_rate: 0.05
lamb: 0.5
device: 'cuda'