_target_: nets.Supervised

backbone: 
  _target_: nets.backbones.resnet18_backbone #nets.backbones.vit_l_16_backbone #nets.backbones.mlp_backbone #nets.whitened_resnet.whitened_resnet18 #

cfg_optim: '<OPTIM>'
num_classes: 2 #3